# [START Wayat Frontend Build]
steps:
  # Cleaning:
  - id: "Cleaning project"
    name: gcr.io/$PROJECT_ID/flutter:stable
    args:
      - clean
    dir: wayat/frontend
  # Dependencies:
  - id: "Getting google-services.json"
    name: gcr.io/cloud-builders/gsutil
    args:
      - cp 
      - 'gs://wayat_secrets/google-services.json'
      - .
    dir: wayat/frontend/android/app
  - id: "Getting key properties"
    name: gcr.io/cloud-builders/gsutil
    args:
      - cp 
      - 'gs://wayat_secrets/key.properties'
      - .
    dir: wayat/frontend/android
  - id: "Getting keystore"
    name: gcr.io/cloud-builders/gsutil
    args:
      - cp 
      - 'gs://wayat_secrets/keystore.jks'
      - .
    dir: wayat
  - id: "Getting env file"
    name: gcr.io/cloud-builders/gsutil
    args:
      - cp
      - 'gs://wayat_secrets/.env'
      - .
    dir: wayat/frontend/
  # Packages:
  - id: "Getting packages"
    name: gcr.io/$PROJECT_ID/flutter:stable
    args:
      - pub
      - get
    dir: wayat/frontend
  # Generated files:
  - id: "Generating extra files"
    name: gcr.io/$PROJECT_ID/flutter:stable
    args:
      - pub
      - run
      - build_runner
      - build
      - --delete-conflicting-outputs
    dir: wayat/frontend
  # Testing:
  # - id: "Running Tests"
  #   name: gcr.io/$PROJECT_ID/flutter:stable
  #   args:
  #     - test
  #   dir: wayat/frontend
  # Release build:
  - id: "Generating APK"
    name: gcr.io/$PROJECT_ID/flutter:stable
    args:
      - build
      - apk
    env:
      - 'ANDROID_API_KEY=${_ANDROID_API_KEY}'
    dir: wayat/frontend
  # Upload build:
  - id: "Uploading APK"
    name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '/workspace/wayat/frontend/build/app/outputs/flutter-apk/app-release.apk', 'gs://wayat_release_apk/wayat_release_$SHORT_SHA.apk']
timeout: "900s"
options: 
  machineType: 'E2_HIGHCPU_8'
# [END Wayat Frontend Build]