import 'package:flutter/material.dart';
import 'package:vertical_letter_bar/page/countries_list_page.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        body: SafeArea(
          child: CountriesListPage( 
            onClickedItem: (item){
              // TODO: SHOW CONTACT INFO
            },
            items: [
              'AFGANISTAN',
              'ALBANIA',
              'ALEMANIA',
              'ANDORRA',
              'ANGOLA',
              'ANGUILLA',
              'ANTIGUA Y BARBUDA',
              'ANTILLAS HOLANDESAS',
              'ARABIA SAUDI',
              'ARGELIA',
              'ARGENTINA',
              'ARMENIA',
              'ARUBA',
              'AUSTRALIA',
              'AUSTRIA',
              'AZERBAIYAN',
              'BAHAMAS',
              'BAHREIN',
              'BANGLADESH',
              'BARBADOS',
              'BELARUS',
              'BELGICA',
              'BELICE',
              'BENIN',
              'BERMUDAS',
              'BHUTÁN',
              'BOLIVIA',
              'BOSNIA Y HERZEGOVINA',
              'BOTSWANA',
              'BRASIL',
              'BRUNEI',
              'BULGARIA',
              'BURKINA FASO',
              'BURUNDI',
              'CABO VERDE',
              'CAMBOYA',
              'CAMERUN',
              'CANADA',
              'CHAD',
              'CHILE',
              'CHINA',
              'CHIPRE',
              'COLOMBIA',
              'COMORES',
              'CONGO',
              'COREA',
              'COREA DEL NORTE ',
              'COSTA DE MARFIL',
              'COSTA RICA',
              'CROACIA',
              'CUBA',
              'DINAMARCA',
              'DJIBOUTI',
              'DOMINICA',
              'ECUADOR',
              'EGIPTO',
              'EL SALVADOR',
              'EMIRATOS ARABES UNIDOS',
              'ERITREA',
              'ESLOVENIA',
              'ESPAÑA',
              'ESTADOS UNIDOS DE AMERICA',
              'ESTONIA',
              'ETIOPIA',
              'FIJI',
              'FILIPINAS',
              'FINLANDIA',
              'FRANCIA',
              'GABON',
              'GAMBIA',
              'GEORGIA',
              'GHANA',
              'GIBRALTAR',
              'GRANADA',
              'GRECIA',
              'GROENLANDIA',
              'GUADALUPE',
              'GUAM',
              'GUATEMALA',
              'GUAYANA FRANCESA',
              'GUERNESEY',
              'GUINEA',
              'GUINEA ECUATORIAL',
              'GUINEA-BISSAU',
              'GUYANA',
              'HAITI',
              'HONDURAS',
              'HONG KONG',
              'HUNGRIA',
              'INDIA',
              'INDONESIA',
              'IRAN',
              'IRAQ',
              'IRLANDA',
              'ISLA DE MAN',
              'ISLA NORFOLK',
              'ISLANDIA',
              'ISLAS ALAND',
              'ISLAS CAIMÁN',
              'ISLAS COOK',
              'ISLAS DEL CANAL',
              'ISLAS FEROE',
              'ISLAS MALVINAS',
              'ISLAS MARIANAS DEL NORTE',
              'ISLAS MARSHALL',
              'ISLAS PITCAIRN',
              'ISLAS SALOMON',
              'ISLAS TURCAS Y CAICOS',
              'ISLAS VIRGENES BRITANICAS',
              'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS',
              'ISRAEL',
              'ITALIA',
              'JAMAICA',
              'JAPON',
              'JERSEY',
              'JORDANIA',
              'KAZAJSTAN',
              'KENIA',
              'KIRGUISTAN',
              'KIRIBATI',
              'KUWAIT',
              'LAOS',
              'LESOTHO',
              'LETONIA',
              'LIBANO',
              'LIBERIA',
              'LIBIA',
              'LIECHTENSTEIN',
              'LITUANIA',
              'LUXEMBURGO',
              'MACAO',
              'MACEDONIA ',
              'MADAGASCAR',
              'MALASIA',
              'MALAWI',
              'MALDIVAS',
              'MALI',
              'MALTA',
              'MARRUECOS',
              'MARTINICA',
              'MAURICIO',
              'MAURITANIA',
              'MAYOTTE',
              'MEXICO',
              'MICRONESIA',
              'MOLDAVIA',
              'MONACO',
              'MONGOLIA',
              'MONTENEGRO',
              'MONTSERRAT',
              'MOZAMBIQUE',
              'MYANMAR',
              'NAMIBIA',
              'NAURU',
              'NEPAL',
              'NICARAGUA',
              'NIGER',
              'NIGERIA',
              'NIUE',
              'NORUEGA',
              'NUEVA CALEDONIA',
              'NUEVA ZELANDA',
              'OMAN',
              'OTROS PAISES  O TERRITORIOS DE AMERICA DEL NORTE',
              'OTROS PAISES O TERRITORIOS  DE SUDAMERICA',
              'OTROS PAISES O TERRITORIOS DE AFRICA',
              'OTROS PAISES O TERRITORIOS DE ASIA',
              'OTROS PAISES O TERRITORIOS DE LA UNION EUROPEA',
              'OTROS PAISES O TERRITORIOS DEL CARIBE Y AMERICA CENTRAL',
              'OTROS PAISES O TERRITORIOS DEL RESTO DE EUROPA',
              'PAISES BAJOS',
              'PAKISTAN',
              'PALAOS',
              'PALESTINA',
              'PANAMA',
              'PAPUA NUEVA GUINEA',
              'PARAGUAY',
              'PERU',
              'POLINESIA FRANCESA',
              'POLONIA',
              'PORTUGAL',
              'PUERTO RICO',
              'QATAR',
              'REINO UNIDO',
              'REP.DEMOCRATICA DEL CONGO',
              'REPUBLICA CENTROAFRICANA',
              'REPUBLICA CHECA',
              'REPUBLICA DOMINICANA',
              'REPUBLICA ESLOVACA',
              'REUNION',
              'RUANDA',
              'RUMANIA',
              'RUSIA',
              'SAHARA OCCIDENTAL',
              'SAMOA',
              'SAMOA AMERICANA',
              'SAN BARTOLOME',
              'SAN CRISTOBAL Y NIEVES',
              'SAN MARINO',
              'SAN MARTIN (PARTE FRANCESA)',
              'SAN PEDRO Y MIQUELON ',
              'SAN VICENTE Y LAS GRANADINAS',
              'SANTA HELENA',
              'SANTA LUCIA',
              'SANTA SEDE',
              'SANTO TOME Y PRINCIPE',
              'SENEGAL',
              'SERBIA',
              'SEYCHELLES',
              'SIERRA LEONA',
              'SINGAPUR',
              'SIRIA',
              'SOMALIA',
              'SRI LANKA',
              'SUDAFRICA',
              'SUDAN',
              'SUECIA',
              'SUIZA',
              'SURINAM',
              'SVALBARD Y JAN MAYEN',
              'SWAZILANDIA',
              'TADYIKISTAN',
              'TAILANDIA',
              'TANZANIA',
              'TIMOR ORIENTAL',
              'TOGO',
              'TOKELAU',
              'TONGA',
              'TRINIDAD Y TOBAGO',
              'TUNEZ',
              'TURKMENISTAN',
              'TURQUIA',
              'TUVALU',
              'UCRANIA',
              'UGANDA',
              'URUGUAY',
              'UZBEKISTAN',
              'VANUATU',
              'VENEZUELA',
              'VIETNAM',
              'WALLIS Y FORTUNA',
              'YEMEN',
              'ZAMBIA',
              'ZIMBABWE'
            ], 
          ),
        )
      ),
    );
  }
}