// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEILvlgyqTS4Kwv5Ed3lKf6ZFHX_1HgTg',
    appId: '1:822297444101:web:62b6a3c4605c526737416c',
    messagingSenderId: '822297444101',
    projectId: 'poc-cloudnative-capgemini',
    authDomain: 'poc-cloudnative-capgemini.firebaseapp.com',
    storageBucket: 'poc-cloudnative-capgemini.appspot.com',
    measurementId: 'G-225V353S4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAsthzXmjfuiGhxRPJq3HEDMwydP4rFIQ',
    appId: '1:822297444101:android:cad962391d75053f37416c',
    messagingSenderId: '822297444101',
    projectId: 'poc-cloudnative-capgemini',
    storageBucket: 'poc-cloudnative-capgemini.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhdgsTf9EcMBs4RBLwRDJAQ4JKyct_hTs',
    appId: '1:822297444101:ios:04dd0c9797c3ec1f37416c',
    messagingSenderId: '822297444101',
    projectId: 'poc-cloudnative-capgemini',
    storageBucket: 'poc-cloudnative-capgemini.appspot.com',
    androidClientId: '822297444101-380u7uderajd71is596bqa3o79dn4g5j.apps.googleusercontent.com',
    iosClientId: '822297444101-l313bbsmn08so8elf7jelje8vduas513.apps.googleusercontent.com',
    iosBundleId: 'com.capgemini.wayat',
  );
}
