// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhe4dqpm16u-mkhR9mg_2g_nQakrhQeps',
    appId: '1:753369751483:android:4fc7131f5def30dd9fae9e',
    messagingSenderId: '753369751483',
    projectId: 'wayat-poc',
    databaseURL: 'https://wayat-poc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wayat-poc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP-AYlpck8Q6U4nDXtoKgL_aDmSeI1SrA',
    appId: '1:753369751483:ios:f62a1bcfd80346759fae9e',
    messagingSenderId: '753369751483',
    projectId: 'wayat-poc',
    databaseURL: 'https://wayat-poc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wayat-poc.appspot.com',
    androidClientId: '753369751483-ejg3fjkjibbcfkdpbadnn2tar4qi1ohr.apps.googleusercontent.com',
    iosClientId: '753369751483-4l7bdl2ps4gl1tv2d6l63n1dasbcan5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneVerification',
  );
}
