name: auto_route_example
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path: ^1.8.1
  auto_route: ^4.2.0
  mobx: ^2.0.7+4
  # MobX widgets
  flutter_mobx: ^2.0.6+1
  # Dependency Injection
  get_it: ^7.2.0
dev_dependencies:
  analyzer: ^4.2.0 
  auto_route_generator: ^4.2.0
  build_runner: ^2.1.5
  # MobX code generator
  mobx_codegen: ^2.0.7
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
