name: auto_route_example
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path: ^1.8.1
  auto_route: ^4.2.0
dev_dependencies:
  analyzer: ^4.2.0 
  auto_route_generator: ^4.2.0
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
