// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQuE7sYC4QmKa5evrBZq2j0AxbPlQQUvA',
    appId: '1:887276025973:web:c7fde0de8546600a5e203c',
    messagingSenderId: '887276025973',
    projectId: 'wayat-flutter',
    authDomain: 'wayat-flutter.firebaseapp.com',
    storageBucket: 'wayat-flutter.appspot.com',
    measurementId: 'G-BLSSR91DZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgT8yt4cmzRkDa0o2i8OtIysNuKDWkwDA',
    appId: '1:887276025973:android:c9ed3ef40b6ccd005e203c',
    messagingSenderId: '887276025973',
    projectId: 'wayat-flutter',
    storageBucket: 'wayat-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjVkDrHneMPPETPX_gAR799lGkppbTdHo',
    appId: '1:887276025973:ios:d8461e155b218a1e5e203c',
    messagingSenderId: '887276025973',
    projectId: 'wayat-flutter',
    storageBucket: 'wayat-flutter.appspot.com',
    iosClientId: '887276025973-74s75sl14f9n4l3pvfgcbm5j6b2ad3qb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterOauthSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjVkDrHneMPPETPX_gAR799lGkppbTdHo',
    appId: '1:887276025973:ios:d8461e155b218a1e5e203c',
    messagingSenderId: '887276025973',
    projectId: 'wayat-flutter',
    storageBucket: 'wayat-flutter.appspot.com',
    iosClientId: '887276025973-74s75sl14f9n4l3pvfgcbm5j6b2ad3qb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterOauthSignin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQuE7sYC4QmKa5evrBZq2j0AxbPlQQUvA',
    appId: '1:887276025973:web:4c93134eb10020fc5e203c',
    messagingSenderId: '887276025973',
    projectId: 'wayat-flutter',
    authDomain: 'wayat-flutter.firebaseapp.com',
    storageBucket: 'wayat-flutter.appspot.com',
    measurementId: 'G-TXR7QRPJGG',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAQuE7sYC4QmKa5evrBZq2j0AxbPlQQUvA',
    appId: '1:887276025973:web:dc3926aa62d8a6465e203c',
    messagingSenderId: '887276025973',
    projectId: 'wayat-flutter',
    authDomain: 'wayat-flutter.firebaseapp.com',
    storageBucket: 'wayat-flutter.appspot.com',
    measurementId: 'G-07CDGKDS6R',
  );
}
