# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml --substitutions _FLUTTER_VERSION=latest

steps:
- name: 'docker:stable'
  args: [
    'build', '.',
    '-t', 'gcr.io/$PROJECT_ID/flutter:stable',
    '--build-arg', 'FLUTTER_VERSION=${_FLUTTER_VERSION}',
  ]
- name: 'docker:stable'
  args: [
    'build', '.',
    '-t', 'gcr.io/$PROJECT_ID/flutter:${_FLUTTER_VERSION}',
    '--build-arg', 'FLUTTER_VERSION=${_FLUTTER_VERSION}',
  ]
- name: 'gcr.io/$PROJECT_ID/flutter:${_FLUTTER_VERSION}'
  args: ['--version']

timeout: '1200s'

images: [
  'gcr.io/$PROJECT_ID/flutter:stable',
  'gcr.io/$PROJECT_ID/flutter:${_FLUTTER_VERSION}',
]
options: 
  machineType: 'E2_HIGHCPU_32'