# [START Wayat Backend Build]
steps:
  - name: gcr.io/cloud-builders/gsutil
    args:
      - cp
      - 'gs://wayat_prod_secrets/firebase.json'
      - .
    dir: wayat/backend
  - name: gcr.io/cloud-builders/gsutil
    args:
      - cp
      - 'gs://wayat_prod_secrets/PROD.env'
      - .
    dir: wayat/backend
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        gcr.io/wayat-prod-capgemini/wayat-flutter-python-mvp:$COMMIT_SHA
      - .
    dir: wayat/backend
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        gcr.io/wayat-prod-capgemini/wayat-flutter-python-mvp:$COMMIT_SHA
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - wayat-api
      - '--image'
      - >-
        gcr.io/wayat-prod-capgemini/wayat-flutter-python-mvp:$COMMIT_SHA
      - '--region'
      - europe-southwest1
    entrypoint: gcloud
images:
  - >-
    gcr.io/wayat-prod-capgemini/wayat-flutter-python-mvp:$COMMIT_SHA
# [END Wayat Backend Build]
