name: mobxandgetit
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State management
  mobx: ^2.0.7+2
  flutter_mobx: ^2.0.6+1
  # Dependency injection
  get_it: ^7.2.0
  # Badges for shopping cart number
  badges: ^2.0.3
  # Counter button
  counter_button:
    git:
      url: https://github.com/airherna/counter_button

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7


flutter:
  uses-material-design: true
