# [START Wayat Frontend Build]
steps:
  # Dependencies:
  - id: "Getting google-services.json"
    name: gcr.io/cloud-builders/gsutil
    args:
      - cp 
      - 'gs://wayat_secrets/google-services.json'
      - .
    dir: wayat/frontend/android/app  
  - id: "Getting env file"
    name: gcr.io/cloud-builders/gsutil
    args:
      - cp
      - 'gs://wayat_secrets/.env'
      - .
    dir: wayat/frontend/android/app  
  # Testing:
  - id: "Running Tests"
    name: gcr.io/$PROJECT_ID/flutter:stable
    args:
      - test
    dir: wayat/frontend
  # Release build:
  - id: "Generating APK"
    name: gcr.io/$PROJECT_ID/flutter:stable
    args:
      - clean
      - |
        flutter build apk
    env:
      - 'GOOGLE_MAPS_KEY=${_GOOGLE_MAPS_KEY}'
    dir: wayat/frontend
    volumes:
    - name: 'build'
      path: '/workspace/wayat/frontend/build'
  # Upload build:
  - id: "Uploading APK"
    name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '/workspace/wayat/frontend/build/app/outputs/flutter-apk/app-release.apk', 'gs://wayat_release_apk/wayat_release_$SHORT_SHA.apk']
    volumes:
    - name: 'build'
      path: '/workspace/wayat/frontend/build'
timeout: "1500s"
# [END Wayat Frontend Build]