# [START Wayat Frontend Build]
steps:
  # Cleaning:
  - id: "Cleaning project"
    name: gcr.io/$PROJECT_ID/flutter:stable
    args:
      - clean
    dir: wayat/frontend
  # Signing report:
  - id: "Signing report"
    name: gcr.io/$PROJECT_ID/flutter:stable
    entrypoint: bash
    args:
      - ./gradlew
      - signingreport
    dir: wayat/frontend/android
  # Dependencies:
  - id: "Getting google-services.json"
    name: gcr.io/cloud-builders/gsutil
    args:
      - cp 
      - 'gs://wayat_secrets/google-services.json'
      - .
    dir: wayat/frontend/android/app
  - id: "Getting env file"
    name: gcr.io/cloud-builders/gsutil
    args:
      - cp
      - 'gs://wayat_secrets/.env'
      - .
    dir: wayat/frontend/
  # Packages:
  - id: "Getting packages"
    name: gcr.io/$PROJECT_ID/flutter:stable
    args:
      - pub
      - get
    dir: wayat/frontend
  # Testing:
  - id: "Running Tests"
    name: gcr.io/$PROJECT_ID/flutter:stable
    args:
      - test
    dir: wayat/frontend
  # Release build:
  - id: "Generating APK"
    name: gcr.io/$PROJECT_ID/flutter:stable
    args:
      - build
      - apk
    env:
      - 'GOOGLE_MAPS_KEY=${_GOOGLE_MAPS_KEY}'
    dir: wayat/frontend
  # Upload build:
  - id: "Uploading APK"
    name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '/workspace/wayat/frontend/build/app/outputs/flutter-apk/app-release.apk', 'gs://wayat_release_apk/wayat_release_$SHORT_SHA.apk']
timeout: "1500s"
# [END Wayat Frontend Build]