name: wayat
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # State management
  mobx: ^2.0.7+4
  # MobX widgets
  flutter_mobx: ^2.0.6+1
  # Dependency Injection
  get_it: ^7.2.0
  # Notification indicator
  badges: ^2.0.3
  # Email validation in forms
  email_validator: ^2.0.1
  # Dependencies for internationalization with flutter:
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  # Routing and navigation
  auto_route: ^4.2.0
  path: ^1.8.1
  # Environment variables
  flutter_config: ^2.0.0
  # Google maps
  google_maps_flutter: ^2.1.10
  # AZ ListView for imported contacts
  azlistview: ^2.0.0
  # Key Value storage
  shared_preferences: ^2.0.15
  # Handles logic to import address books contacts
  flutter_contacts: ^1.1.5
  # Google Sign In
  google_sign_in: ^5.4.0
  # Http request for backend
  http: ^0.13.4
  # Decoding Token ID
  jwt_decode: ^0.3.1
  # Phone validation
  phone_number: ^0.12.0+2
  # Phone textfield with countries
  intl_phone_field: ^3.1.0
  #Location
  location: ^4.4.0
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  flutter_cache_manager: ^3.3.0
  image: ^3.2.0
  # For the x minutes ago in the Pop Up for the Map contacts
  timeago: ^3.2.2
  # To launch google maps app
  url_launcher: ^6.1.5
  #Firebase dependencies
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.3
  firebase_auth: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  # AutoRoute dependencies for code generation
  analyzer: ^4.2.0 
  auto_route_generator: ^4.2.0
  # Process that generates code for AutoRoute and MobX
  build_runner: ^2.1.5
  # MobX code generator
  mobx_codegen: ^2.0.7
  # Dialogs
  speech_balloon: ^0.0.4


flutter:
  # Flag to generate internationalization files
  generate: true

  uses-material-design: true
  assets:
    - .env
    - assets/images/