name: wayat
description: An application to share location with friends and acquaintances
publish_to: 'none' 
version: 0.5.0+8

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # State management
  mobx: ^2.0.7+4
  # MobX widgets
  flutter_mobx: ^2.0.6+1
  # Dependency Injection
  get_it: ^7.2.0
  # Notification indicator
  badges: ^2.0.3
  # Email validation in forms
  email_validator: ^2.0.1
  # Dependencies for internationalization with flutter:
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  path: ^1.8.1
  # Location services
  location: ^4.4.0
  # Environment variables
  flutter_dotenv: ^5.0.2
  # Google maps
  google_maps_flutter: ^2.2.0
  # AZ ListView for imported contacts
  azlistview: ^2.0.0
  # Key Value storage
  shared_preferences: ^2.0.15
  # Handles logic to import address books contacts
  flutter_contacts: ^1.1.5
  # Google Sign In
  google_sign_in: ^5.4.2
  google_sign_in_dartio: ^0.2.1
  # Http request for backend
  http: ^0.13.4
  # Decoding Token ID
  jwt_decode: ^0.3.1
  # Phone validation
  phone_number: ^1.0.0
  # Phone textfield with countries
  intl_phone_field: ^3.1.0
  json_annotation: ^4.6.0
  flutter_cache_manager: ^3.3.0
  image: ^3.2.0
  # For the x minutes ago in the Pop Up for the Map contacts
  timeago: ^3.3.0
  # To launch google maps app
  url_launcher: ^6.1.5
  # Firebase dependencies
  firebase_core_platform_interface: ^4.5.2
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.3
  firebase_auth: ^4.1.0
  firebase_messaging: ^14.0.3
  image_picker: ^0.8.5+3
  # Phone verification
  firebase_phone_auth_handler: ^1.0.6
  firebase_auth_platform_interface: ^6.1.10
  pinput: ^2.2.12
  smart_auth: ^1.0.5
  # Testing mocks
  mockito: ^5.3.0
  # Web dependencies
  google_maps_flutter_web: ^0.4.0+2
  # Icon generation
  flutter_launcher_icons: ^0.10.0
  # Platform app dependencies
  restart_app: ^1.1.0+1
  app_settings: ^4.1.8
  # Fix url in web
  url_strategy: ^0.2.0
  # Synchronization
  synchronized: ^3.0.0+3
  # Flutter map
  flutter_map: ^3.0.0
  latlong2: ^0.8.1
  # Navigation
  go_router: ^5.1.0
  # Notifications inside the app
  flutter_local_notifications: ^12.0.3
  overlay_support: ^2.0.1
  # Scaffold that automatically resizes with the screen
  adaptive_navigation: ^0.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  # AutoRoute dependencies for code generation
  analyzer: ^4.2.0 
  # Process that generates code for AutoRoute and MobX
  build_runner: ^2.1.5
  # MobX code generator
  mobx_codegen: ^2.0.7
  # Dialogs
  speech_balloon: ^0.0.4
  remove_from_coverage: 2.0.0
  # Data class generator
  json_serializable: ^6.3.1

flutter:
  # Flag to generate internationalization files
  generate: true

  uses-material-design: true
  assets:
    - testenv
    - .env
    - assets/images/
  
flutter_icons:
  android: true
  image_path_android: 'assets/images/wayat_icon.png'
  ios: true
  image_path_ios: 'assets/images/wayat_icon.png'
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/wayat_icon.png"
  windows:
    generate: true
    image_path: "assets/images/wayat_icon.png"
    icon_size: 48 # min:48, max:256, default: 48