---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  cloud_run:
    format: "{\"severity\": \"%(levelname)s\", \"component\": \"%(name)s\", \"message\": \"%(message)s\", \"timestamp\": \"%(asctime)-s\"}"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: cloud_run
    stream: ext://sys.stdout

root:
  level: DEBUG
  handlers: [console]