// Mocks generated by Mockito 5.3.0 from annotations
// in wayat/test/services/common/http_provider/http_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:convert' as _i7;
import 'dart:typed_data' as _i8;

import 'package:google_sign_in/google_sign_in.dart' as _i9;
import 'package:http/http.dart' as _i2;
import 'package:mobx/mobx.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wayat/app_state/user_session/session_state.dart' as _i10;
import 'package:wayat/domain/user/my_user.dart' as _i3;
import 'package:wayat/services/authentication/auth_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeStreamedResponse_1 extends _i1.SmartFake
    implements _i2.StreamedResponse {
  _FakeStreamedResponse_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeMyUser_2 extends _i1.SmartFake implements _i3.MyUser {
  _FakeMyUser_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeAuthService_3 extends _i1.SmartFake implements _i4.AuthService {
  _FakeAuthService_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeReactiveContext_4 extends _i1.SmartFake
    implements _i5.ReactiveContext {
  _FakeReactiveContext_4(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i2.Client {
  @override
  _i6.Future<_i2.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
                  this, Invocation.method(#head, [url], {#headers: headers}))),
              returnValueForMissingStub: _i6.Future<_i2.Response>.value(
                  _FakeResponse_0(this,
                      Invocation.method(#head, [url], {#headers: headers}))))
          as _i6.Future<_i2.Response>);
  @override
  _i6.Future<_i2.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
                  this, Invocation.method(#get, [url], {#headers: headers}))),
              returnValueForMissingStub: _i6.Future<_i2.Response>.value(
                  _FakeResponse_0(this,
                      Invocation.method(#get, [url], {#headers: headers}))))
          as _i6.Future<_i2.Response>);
  @override
  _i6.Future<_i2.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i7.Encoding? encoding}) =>
      (super.noSuchMethod(Invocation.method(#post, [url], {#headers: headers, #body: body, #encoding: encoding}),
          returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
              this,
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}))),
          returnValueForMissingStub: _i6.Future<_i2.Response>.value(
              _FakeResponse_0(this, Invocation.method(#post, [url], {#headers: headers, #body: body, #encoding: encoding})))) as _i6.Future<_i2.Response>);
  @override
  _i6.Future<_i2.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i7.Encoding? encoding}) =>
      (super.noSuchMethod(Invocation.method(#put, [url], {#headers: headers, #body: body, #encoding: encoding}),
          returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
              this,
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}))),
          returnValueForMissingStub: _i6.Future<_i2.Response>.value(
              _FakeResponse_0(this, Invocation.method(#put, [url], {#headers: headers, #body: body, #encoding: encoding})))) as _i6.Future<_i2.Response>);
  @override
  _i6.Future<_i2.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i7.Encoding? encoding}) =>
      (super.noSuchMethod(Invocation.method(#patch, [url], {#headers: headers, #body: body, #encoding: encoding}),
          returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
              this,
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}))),
          returnValueForMissingStub: _i6.Future<_i2.Response>.value(
              _FakeResponse_0(this, Invocation.method(#patch, [url], {#headers: headers, #body: body, #encoding: encoding})))) as _i6.Future<_i2.Response>);
  @override
  _i6.Future<_i2.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i7.Encoding? encoding}) =>
      (super.noSuchMethod(Invocation.method(#delete, [url], {#headers: headers, #body: body, #encoding: encoding}),
          returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
              this,
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}))),
          returnValueForMissingStub: _i6.Future<_i2.Response>.value(
              _FakeResponse_0(this, Invocation.method(#delete, [url], {#headers: headers, #body: body, #encoding: encoding})))) as _i6.Future<_i2.Response>);
  @override
  _i6.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
              returnValue: _i6.Future<String>.value(''),
              returnValueForMissingStub: _i6.Future<String>.value(''))
          as _i6.Future<String>);
  @override
  _i6.Future<_i8.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: _i6.Future<_i8.Uint8List>.value(_i8.Uint8List(0)),
              returnValueForMissingStub:
                  _i6.Future<_i8.Uint8List>.value(_i8.Uint8List(0)))
          as _i6.Future<_i8.Uint8List>);
  @override
  _i6.Future<_i2.StreamedResponse> send(_i2.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue: _i6.Future<_i2.StreamedResponse>.value(
                  _FakeStreamedResponse_1(
                      this, Invocation.method(#send, [request]))),
              returnValueForMissingStub: _i6.Future<_i2.StreamedResponse>.value(
                  _FakeStreamedResponse_1(
                      this, Invocation.method(#send, [request]))))
          as _i6.Future<_i2.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  @override
  _i6.Future<_i9.GoogleSignInAccount?> signIn() =>
      (super.noSuchMethod(Invocation.method(#signIn, []),
              returnValue: _i6.Future<_i9.GoogleSignInAccount?>.value(),
              returnValueForMissingStub:
                  _i6.Future<_i9.GoogleSignInAccount?>.value())
          as _i6.Future<_i9.GoogleSignInAccount?>);
  @override
  _i6.Future<String> getIdToken() =>
      (super.noSuchMethod(Invocation.method(#getIdToken, []),
              returnValue: _i6.Future<String>.value(''),
              returnValueForMissingStub: _i6.Future<String>.value(''))
          as _i6.Future<String>);
  @override
  _i6.Future<void> signOut() => (super.noSuchMethod(
      Invocation.method(#signOut, []),
      returnValue: _i6.Future<void>.value(),
      returnValueForMissingStub: _i6.Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<_i3.MyUser> getUserData() =>
      (super.noSuchMethod(Invocation.method(#getUserData, []),
              returnValue: _i6.Future<_i3.MyUser>.value(
                  _FakeMyUser_2(this, Invocation.method(#getUserData, []))),
              returnValueForMissingStub: _i6.Future<_i3.MyUser>.value(
                  _FakeMyUser_2(this, Invocation.method(#getUserData, []))))
          as _i6.Future<_i3.MyUser>);
  @override
  _i6.Future<_i9.GoogleSignInAccount?> signInSilently() =>
      (super.noSuchMethod(Invocation.method(#signInSilently, []),
              returnValue: _i6.Future<_i9.GoogleSignInAccount?>.value(),
              returnValueForMissingStub:
                  _i6.Future<_i9.GoogleSignInAccount?>.value())
          as _i6.Future<_i9.GoogleSignInAccount?>);
  @override
  _i6.Future<bool> sendPhoneNumber(String? phone) =>
      (super.noSuchMethod(Invocation.method(#sendPhoneNumber, [phone]),
              returnValue: _i6.Future<bool>.value(false),
              returnValueForMissingStub: _i6.Future<bool>.value(false))
          as _i6.Future<bool>);
  @override
  _i6.Future<bool> sendDoneOnboarding(bool? doneOnboarding) =>
      (super.noSuchMethod(
              Invocation.method(#sendDoneOnboarding, [doneOnboarding]),
              returnValue: _i6.Future<bool>.value(false),
              returnValueForMissingStub: _i6.Future<bool>.value(false))
          as _i6.Future<bool>);
}

/// A class which mocks [SessionState].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionState extends _i1.Mock implements _i10.SessionState {
  @override
  bool get finishLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#finishLoggedIn),
          returnValue: false, returnValueForMissingStub: false) as bool);
  @override
  set finishLoggedIn(bool? value) =>
      super.noSuchMethod(Invocation.setter(#finishLoggedIn, value),
          returnValueForMissingStub: null);
  @override
  bool get googleSignedIn =>
      (super.noSuchMethod(Invocation.getter(#googleSignedIn),
          returnValue: false, returnValueForMissingStub: false) as bool);
  @override
  set googleSignedIn(bool? value) =>
      super.noSuchMethod(Invocation.setter(#googleSignedIn, value),
          returnValueForMissingStub: null);
  @override
  bool get hasDoneOnboarding =>
      (super.noSuchMethod(Invocation.getter(#hasDoneOnboarding),
          returnValue: false, returnValueForMissingStub: false) as bool);
  @override
  set hasDoneOnboarding(bool? value) =>
      super.noSuchMethod(Invocation.setter(#hasDoneOnboarding, value),
          returnValueForMissingStub: null);
  @override
  set currentUser(_i3.MyUser? value) =>
      super.noSuchMethod(Invocation.setter(#currentUser, value),
          returnValueForMissingStub: null);
  @override
  _i4.AuthService get authService => (super.noSuchMethod(
      Invocation.getter(#authService),
      returnValue: _FakeAuthService_3(this, Invocation.getter(#authService)),
      returnValueForMissingStub: _FakeAuthService_3(
          this, Invocation.getter(#authService))) as _i4.AuthService);
  @override
  _i5.ReactiveContext get context => (super.noSuchMethod(
      Invocation.getter(#context),
      returnValue: _FakeReactiveContext_4(this, Invocation.getter(#context)),
      returnValueForMissingStub: _FakeReactiveContext_4(
          this, Invocation.getter(#context))) as _i5.ReactiveContext);
  @override
  _i6.Future<void> doneOnBoarding() => (super.noSuchMethod(
      Invocation.method(#doneOnBoarding, []),
      returnValue: _i6.Future<void>.value(),
      returnValueForMissingStub: _i6.Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<void> isLogged() => (super.noSuchMethod(
      Invocation.method(#isLogged, []),
      returnValue: _i6.Future<void>.value(),
      returnValueForMissingStub: _i6.Future<void>.value()) as _i6.Future<void>);
  @override
  void setGoogleSignIn(bool? signedIn) =>
      super.noSuchMethod(Invocation.method(#setGoogleSignIn, [signedIn]),
          returnValueForMissingStub: null);
  @override
  void setFinishLoggedIn(bool? finishedLoggedIn) => super.noSuchMethod(
      Invocation.method(#setFinishLoggedIn, [finishedLoggedIn]),
      returnValueForMissingStub: null);
  @override
  _i6.Future<dynamic> initializeUser() =>
      (super.noSuchMethod(Invocation.method(#initializeUser, []),
              returnValue: _i6.Future<dynamic>.value(),
              returnValueForMissingStub: _i6.Future<dynamic>.value())
          as _i6.Future<dynamic>);
  @override
  _i6.Future<dynamic> updateCurrentUser() =>
      (super.noSuchMethod(Invocation.method(#updateCurrentUser, []),
              returnValue: _i6.Future<dynamic>.value(),
              returnValueForMissingStub: _i6.Future<dynamic>.value())
          as _i6.Future<dynamic>);
  @override
  _i6.Future<bool> updatePhone(String? phone) =>
      (super.noSuchMethod(Invocation.method(#updatePhone, [phone]),
              returnValue: _i6.Future<bool>.value(false),
              returnValueForMissingStub: _i6.Future<bool>.value(false))
          as _i6.Future<bool>);
  @override
  _i6.Future<bool> setDoneOnBoarding() =>
      (super.noSuchMethod(Invocation.method(#setDoneOnBoarding, []),
              returnValue: _i6.Future<bool>.value(false),
              returnValueForMissingStub: _i6.Future<bool>.value(false))
          as _i6.Future<bool>);
  @override
  _i6.Future<dynamic> doLoginProcess() =>
      (super.noSuchMethod(Invocation.method(#doLoginProcess, []),
              returnValue: _i6.Future<dynamic>.value(),
              returnValueForMissingStub: _i6.Future<dynamic>.value())
          as _i6.Future<dynamic>);
  @override
  _i6.Future<dynamic> initializeUserSession() =>
      (super.noSuchMethod(Invocation.method(#initializeUserSession, []),
              returnValue: _i6.Future<dynamic>.value(),
              returnValueForMissingStub: _i6.Future<dynamic>.value())
          as _i6.Future<dynamic>);
  @override
  _i6.Future<void> login() => (super.noSuchMethod(Invocation.method(#login, []),
      returnValue: _i6.Future<void>.value(),
      returnValueForMissingStub: _i6.Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<dynamic> logOut() =>
      (super.noSuchMethod(Invocation.method(#logOut, []),
              returnValue: _i6.Future<dynamic>.value(),
              returnValueForMissingStub: _i6.Future<dynamic>.value())
          as _i6.Future<dynamic>);
  @override
  bool isOnboardingCompleted() =>
      (super.noSuchMethod(Invocation.method(#isOnboardingCompleted, []),
          returnValue: false, returnValueForMissingStub: false) as bool);
  @override
  bool hasPhone() => (super.noSuchMethod(Invocation.method(#hasPhone, []),
      returnValue: false, returnValueForMissingStub: false) as bool);
}
