// Mocks generated by Mockito 5.3.0 from annotations
// in wayat/test/onboarding_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter/cupertino.dart' as _i12;
import 'package:mobx/mobx.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wayat/app_state/user_session/session_state.dart' as _i5;
import 'package:wayat/domain/contact/contact.dart' as _i11;
import 'package:wayat/domain/user/my_user.dart' as _i6;
import 'package:wayat/features/onboarding/controller/onboarding_controller.dart'
    as _i8;
import 'package:wayat/features/onboarding/controller/onboarding_progress.dart'
    as _i10;
import 'package:wayat/features/onboarding/controller/onboarding_state.dart'
    as _i9;
import 'package:wayat/services/authentication/auth_service.dart' as _i2;
import 'package:wayat/services/contact/contact_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthService_0 extends _i1.SmartFake implements _i2.AuthService {
  _FakeAuthService_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeReactiveContext_1 extends _i1.SmartFake
    implements _i3.ReactiveContext {
  _FakeReactiveContext_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeContactService_2 extends _i1.SmartFake
    implements _i4.ContactService {
  _FakeContactService_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeObservableMap_3<K, V> extends _i1.SmartFake
    implements _i3.ObservableMap<K, V> {
  _FakeObservableMap_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [SessionState].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionState extends _i1.Mock implements _i5.SessionState {
  MockSessionState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get finishLoggedIn => (super
          .noSuchMethod(Invocation.getter(#finishLoggedIn), returnValue: false)
      as bool);
  @override
  set finishLoggedIn(bool? value) =>
      super.noSuchMethod(Invocation.setter(#finishLoggedIn, value),
          returnValueForMissingStub: null);
  @override
  bool get googleSignedIn => (super
          .noSuchMethod(Invocation.getter(#googleSignedIn), returnValue: false)
      as bool);
  @override
  set googleSignedIn(bool? value) =>
      super.noSuchMethod(Invocation.setter(#googleSignedIn, value),
          returnValueForMissingStub: null);
  @override
  bool get hasDoneOnboarding =>
      (super.noSuchMethod(Invocation.getter(#hasDoneOnboarding),
          returnValue: false) as bool);
  @override
  set hasDoneOnboarding(bool? value) =>
      super.noSuchMethod(Invocation.setter(#hasDoneOnboarding, value),
          returnValueForMissingStub: null);
  @override
  set currentUser(_i6.MyUser? value) =>
      super.noSuchMethod(Invocation.setter(#currentUser, value),
          returnValueForMissingStub: null);
  @override
  _i2.AuthService get authService =>
      (super.noSuchMethod(Invocation.getter(#authService),
              returnValue:
                  _FakeAuthService_0(this, Invocation.getter(#authService)))
          as _i2.AuthService);
  @override
  _i3.ReactiveContext get context =>
      (super.noSuchMethod(Invocation.getter(#context),
              returnValue:
                  _FakeReactiveContext_1(this, Invocation.getter(#context)))
          as _i3.ReactiveContext);
  @override
  _i7.Future<void> doneOnBoarding() => (super.noSuchMethod(
      Invocation.method(#doneOnBoarding, []),
      returnValue: _i7.Future<void>.value(),
      returnValueForMissingStub: _i7.Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<dynamic> isLogged() =>
      (super.noSuchMethod(Invocation.method(#isLogged, []),
          returnValue: _i7.Future<dynamic>.value()) as _i7.Future<dynamic>);
  @override
  void setGoogleSignIn(bool? signedIn) =>
      super.noSuchMethod(Invocation.method(#setGoogleSignIn, [signedIn]),
          returnValueForMissingStub: null);
  @override
  void setFinishLoggedIn(bool? finishedLoggedIn) => super.noSuchMethod(
      Invocation.method(#setFinishLoggedIn, [finishedLoggedIn]),
      returnValueForMissingStub: null);
  @override
  _i7.Future<dynamic> updateCurrentUser() =>
      (super.noSuchMethod(Invocation.method(#updateCurrentUser, []),
          returnValue: _i7.Future<dynamic>.value()) as _i7.Future<dynamic>);
  @override
  _i7.Future<bool> updatePhone(String? phone) =>
      (super.noSuchMethod(Invocation.method(#updatePhone, [phone]),
          returnValue: _i7.Future<bool>.value(false)) as _i7.Future<bool>);
  @override
  _i7.Future<bool> updateOnboarding() =>
      (super.noSuchMethod(Invocation.method(#updateOnboarding, []),
          returnValue: _i7.Future<bool>.value(false)) as _i7.Future<bool>);
  @override
  _i7.Future<dynamic> doLoginProcess() =>
      (super.noSuchMethod(Invocation.method(#doLoginProcess, []),
          returnValue: _i7.Future<dynamic>.value()) as _i7.Future<dynamic>);
  @override
  _i7.Future<dynamic> initializeUserSession() =>
      (super.noSuchMethod(Invocation.method(#initializeUserSession, []),
          returnValue: _i7.Future<dynamic>.value()) as _i7.Future<dynamic>);
  @override
  _i7.Future<dynamic> login() =>
      (super.noSuchMethod(Invocation.method(#login, []),
          returnValue: _i7.Future<dynamic>.value()) as _i7.Future<dynamic>);
  @override
  bool isOnboardingCompleted() =>
      (super.noSuchMethod(Invocation.method(#isOnboardingCompleted, []),
          returnValue: false) as bool);
  @override
  bool hasPhone() =>
      (super.noSuchMethod(Invocation.method(#hasPhone, []), returnValue: false)
          as bool);
}

/// A class which mocks [OnboardingController].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnboardingController extends _i1.Mock
    implements _i8.OnboardingController {
  MockOnboardingController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ContactService get contactService => (super.noSuchMethod(
          Invocation.getter(#contactService),
          returnValue:
              _FakeContactService_2(this, Invocation.getter(#contactService)))
      as _i4.ContactService);
  @override
  set contactService(_i4.ContactService? _contactService) =>
      super.noSuchMethod(Invocation.setter(#contactService, _contactService),
          returnValueForMissingStub: null);
  @override
  _i9.OnBoardingState get onBoardingState =>
      (super.noSuchMethod(Invocation.getter(#onBoardingState),
          returnValue: _i9.OnBoardingState.NotStarted) as _i9.OnBoardingState);
  @override
  set onBoardingState(_i9.OnBoardingState? value) =>
      super.noSuchMethod(Invocation.setter(#onBoardingState, value),
          returnValueForMissingStub: null);
  @override
  _i10.OnBoardingProgress get currentPage =>
      (super.noSuchMethod(Invocation.getter(#currentPage),
              returnValue: _i10.OnBoardingProgress.initialManageContactsTip)
          as _i10.OnBoardingProgress);
  @override
  set currentPage(_i10.OnBoardingProgress? value) =>
      super.noSuchMethod(Invocation.setter(#currentPage, value),
          returnValueForMissingStub: null);
  @override
  _i3.ObservableMap<_i11.Contact, bool> get contacts =>
      (super.noSuchMethod(Invocation.getter(#contacts),
              returnValue: _FakeObservableMap_3<_i11.Contact, bool>(
                  this, Invocation.getter(#contacts)))
          as _i3.ObservableMap<_i11.Contact, bool>);
  @override
  set contacts(_i3.ObservableMap<_i11.Contact, bool>? value) =>
      super.noSuchMethod(Invocation.setter(#contacts, value),
          returnValueForMissingStub: null);
  @override
  List<_i11.Contact> get contactList =>
      (super.noSuchMethod(Invocation.getter(#contactList),
          returnValue: <_i11.Contact>[]) as List<_i11.Contact>);
  @override
  List<_i11.Contact> get selectedContacts =>
      (super.noSuchMethod(Invocation.getter(#selectedContacts),
          returnValue: <_i11.Contact>[]) as List<_i11.Contact>);
  @override
  List<_i11.Contact> get unselectedContacts =>
      (super.noSuchMethod(Invocation.getter(#unselectedContacts),
          returnValue: <_i11.Contact>[]) as List<_i11.Contact>);
  @override
  _i3.ReactiveContext get context =>
      (super.noSuchMethod(Invocation.getter(#context),
              returnValue:
                  _FakeReactiveContext_1(this, Invocation.getter(#context)))
          as _i3.ReactiveContext);
  @override
  void importContacts() =>
      super.noSuchMethod(Invocation.method(#importContacts, []),
          returnValueForMissingStub: null);
  @override
  bool isSelected(_i11.Contact? contact) =>
      (super.noSuchMethod(Invocation.method(#isSelected, [contact]),
          returnValue: false) as bool);
  @override
  void finishOnBoarding(_i12.BuildContext? context) =>
      super.noSuchMethod(Invocation.method(#finishOnBoarding, [context]),
          returnValueForMissingStub: null);
  @override
  void progressTo(_i10.OnBoardingProgress? newPage) =>
      super.noSuchMethod(Invocation.method(#progressTo, [newPage]),
          returnValueForMissingStub: null);
  @override
  bool moveBack() =>
      (super.noSuchMethod(Invocation.method(#moveBack, []), returnValue: false)
          as bool);
  @override
  void updateSelected(_i11.Contact? contact) =>
      super.noSuchMethod(Invocation.method(#updateSelected, [contact]),
          returnValueForMissingStub: null);
  @override
  void addAll(List<_i11.Contact>? contactList) =>
      super.noSuchMethod(Invocation.method(#addAll, [contactList]),
          returnValueForMissingStub: null);
  @override
  void setOnBoardingState(_i9.OnBoardingState? state) =>
      super.noSuchMethod(Invocation.method(#setOnBoardingState, [state]),
          returnValueForMissingStub: null);
}

/// A class which mocks [SessionState].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionStateRelaxed extends _i1.Mock implements _i5.SessionState {
  @override
  bool get finishLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#finishLoggedIn),
          returnValue: false, returnValueForMissingStub: false) as bool);
  @override
  set finishLoggedIn(bool? value) =>
      super.noSuchMethod(Invocation.setter(#finishLoggedIn, value),
          returnValueForMissingStub: null);
  @override
  bool get googleSignedIn =>
      (super.noSuchMethod(Invocation.getter(#googleSignedIn),
          returnValue: false, returnValueForMissingStub: false) as bool);
  @override
  set googleSignedIn(bool? value) =>
      super.noSuchMethod(Invocation.setter(#googleSignedIn, value),
          returnValueForMissingStub: null);
  @override
  bool get hasDoneOnboarding =>
      (super.noSuchMethod(Invocation.getter(#hasDoneOnboarding),
          returnValue: false, returnValueForMissingStub: false) as bool);
  @override
  set hasDoneOnboarding(bool? value) =>
      super.noSuchMethod(Invocation.setter(#hasDoneOnboarding, value),
          returnValueForMissingStub: null);
  @override
  set currentUser(_i6.MyUser? value) =>
      super.noSuchMethod(Invocation.setter(#currentUser, value),
          returnValueForMissingStub: null);
  @override
  _i2.AuthService get authService => (super.noSuchMethod(
      Invocation.getter(#authService),
      returnValue: _FakeAuthService_0(this, Invocation.getter(#authService)),
      returnValueForMissingStub: _FakeAuthService_0(
          this, Invocation.getter(#authService))) as _i2.AuthService);
  @override
  _i3.ReactiveContext get context => (super.noSuchMethod(
      Invocation.getter(#context),
      returnValue: _FakeReactiveContext_1(this, Invocation.getter(#context)),
      returnValueForMissingStub: _FakeReactiveContext_1(
          this, Invocation.getter(#context))) as _i3.ReactiveContext);
  @override
  _i7.Future<void> doneOnBoarding() => (super.noSuchMethod(
      Invocation.method(#doneOnBoarding, []),
      returnValue: _i7.Future<void>.value(),
      returnValueForMissingStub: _i7.Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<dynamic> isLogged() =>
      (super.noSuchMethod(Invocation.method(#isLogged, []),
              returnValue: _i7.Future<dynamic>.value(),
              returnValueForMissingStub: _i7.Future<dynamic>.value())
          as _i7.Future<dynamic>);
  @override
  void setGoogleSignIn(bool? signedIn) =>
      super.noSuchMethod(Invocation.method(#setGoogleSignIn, [signedIn]),
          returnValueForMissingStub: null);
  @override
  void setFinishLoggedIn(bool? finishedLoggedIn) => super.noSuchMethod(
      Invocation.method(#setFinishLoggedIn, [finishedLoggedIn]),
      returnValueForMissingStub: null);
  @override
  _i7.Future<dynamic> updateCurrentUser() =>
      (super.noSuchMethod(Invocation.method(#updateCurrentUser, []),
              returnValue: _i7.Future<dynamic>.value(),
              returnValueForMissingStub: _i7.Future<dynamic>.value())
          as _i7.Future<dynamic>);
  @override
  _i7.Future<bool> updatePhone(String? phone) =>
      (super.noSuchMethod(Invocation.method(#updatePhone, [phone]),
              returnValue: _i7.Future<bool>.value(false),
              returnValueForMissingStub: _i7.Future<bool>.value(false))
          as _i7.Future<bool>);
  @override
  _i7.Future<bool> updateOnboarding() =>
      (super.noSuchMethod(Invocation.method(#updateOnboarding, []),
              returnValue: _i7.Future<bool>.value(false),
              returnValueForMissingStub: _i7.Future<bool>.value(false))
          as _i7.Future<bool>);
  @override
  _i7.Future<dynamic> doLoginProcess() =>
      (super.noSuchMethod(Invocation.method(#doLoginProcess, []),
              returnValue: _i7.Future<dynamic>.value(),
              returnValueForMissingStub: _i7.Future<dynamic>.value())
          as _i7.Future<dynamic>);
  @override
  _i7.Future<dynamic> initializeUserSession() =>
      (super.noSuchMethod(Invocation.method(#initializeUserSession, []),
              returnValue: _i7.Future<dynamic>.value(),
              returnValueForMissingStub: _i7.Future<dynamic>.value())
          as _i7.Future<dynamic>);
  @override
  _i7.Future<dynamic> login() =>
      (super.noSuchMethod(Invocation.method(#login, []),
              returnValue: _i7.Future<dynamic>.value(),
              returnValueForMissingStub: _i7.Future<dynamic>.value())
          as _i7.Future<dynamic>);
  @override
  bool isOnboardingCompleted() =>
      (super.noSuchMethod(Invocation.method(#isOnboardingCompleted, []),
          returnValue: false, returnValueForMissingStub: false) as bool);
  @override
  bool hasPhone() => (super.noSuchMethod(Invocation.method(#hasPhone, []),
      returnValue: false, returnValueForMissingStub: false) as bool);
}

/// A class which mocks [OnboardingController].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnboardingRelaxed extends _i1.Mock
    implements _i8.OnboardingController {
  @override
  _i4.ContactService get contactService => (super.noSuchMethod(
          Invocation.getter(#contactService),
          returnValue:
              _FakeContactService_2(this, Invocation.getter(#contactService)),
          returnValueForMissingStub:
              _FakeContactService_2(this, Invocation.getter(#contactService)))
      as _i4.ContactService);
  @override
  set contactService(_i4.ContactService? _contactService) =>
      super.noSuchMethod(Invocation.setter(#contactService, _contactService),
          returnValueForMissingStub: null);
  @override
  _i9.OnBoardingState get onBoardingState =>
      (super.noSuchMethod(Invocation.getter(#onBoardingState),
              returnValue: _i9.OnBoardingState.NotStarted,
              returnValueForMissingStub: _i9.OnBoardingState.NotStarted)
          as _i9.OnBoardingState);
  @override
  set onBoardingState(_i9.OnBoardingState? value) =>
      super.noSuchMethod(Invocation.setter(#onBoardingState, value),
          returnValueForMissingStub: null);
  @override
  _i10.OnBoardingProgress get currentPage =>
      (super.noSuchMethod(Invocation.getter(#currentPage),
          returnValue: _i10.OnBoardingProgress.initialManageContactsTip,
          returnValueForMissingStub: _i10.OnBoardingProgress
              .initialManageContactsTip) as _i10.OnBoardingProgress);
  @override
  set currentPage(_i10.OnBoardingProgress? value) =>
      super.noSuchMethod(Invocation.setter(#currentPage, value),
          returnValueForMissingStub: null);
  @override
  _i3.ObservableMap<_i11.Contact, bool> get contacts => (super.noSuchMethod(
          Invocation.getter(#contacts),
          returnValue: _FakeObservableMap_3<_i11.Contact, bool>(
              this, Invocation.getter(#contacts)),
          returnValueForMissingStub: _FakeObservableMap_3<_i11.Contact, bool>(
              this, Invocation.getter(#contacts)))
      as _i3.ObservableMap<_i11.Contact, bool>);
  @override
  set contacts(_i3.ObservableMap<_i11.Contact, bool>? value) =>
      super.noSuchMethod(Invocation.setter(#contacts, value),
          returnValueForMissingStub: null);
  @override
  List<_i11.Contact> get contactList =>
      (super.noSuchMethod(Invocation.getter(#contactList),
          returnValue: <_i11.Contact>[],
          returnValueForMissingStub: <_i11.Contact>[]) as List<_i11.Contact>);
  @override
  List<_i11.Contact> get selectedContacts =>
      (super.noSuchMethod(Invocation.getter(#selectedContacts),
          returnValue: <_i11.Contact>[],
          returnValueForMissingStub: <_i11.Contact>[]) as List<_i11.Contact>);
  @override
  List<_i11.Contact> get unselectedContacts =>
      (super.noSuchMethod(Invocation.getter(#unselectedContacts),
          returnValue: <_i11.Contact>[],
          returnValueForMissingStub: <_i11.Contact>[]) as List<_i11.Contact>);
  @override
  _i3.ReactiveContext get context => (super.noSuchMethod(
      Invocation.getter(#context),
      returnValue: _FakeReactiveContext_1(this, Invocation.getter(#context)),
      returnValueForMissingStub: _FakeReactiveContext_1(
          this, Invocation.getter(#context))) as _i3.ReactiveContext);
  @override
  void importContacts() =>
      super.noSuchMethod(Invocation.method(#importContacts, []),
          returnValueForMissingStub: null);
  @override
  bool isSelected(_i11.Contact? contact) =>
      (super.noSuchMethod(Invocation.method(#isSelected, [contact]),
          returnValue: false, returnValueForMissingStub: false) as bool);
  @override
  void finishOnBoarding(_i12.BuildContext? context) =>
      super.noSuchMethod(Invocation.method(#finishOnBoarding, [context]),
          returnValueForMissingStub: null);
  @override
  void progressTo(_i10.OnBoardingProgress? newPage) =>
      super.noSuchMethod(Invocation.method(#progressTo, [newPage]),
          returnValueForMissingStub: null);
  @override
  bool moveBack() => (super.noSuchMethod(Invocation.method(#moveBack, []),
      returnValue: false, returnValueForMissingStub: false) as bool);
  @override
  void updateSelected(_i11.Contact? contact) =>
      super.noSuchMethod(Invocation.method(#updateSelected, [contact]),
          returnValueForMissingStub: null);
  @override
  void addAll(List<_i11.Contact>? contactList) =>
      super.noSuchMethod(Invocation.method(#addAll, [contactList]),
          returnValueForMissingStub: null);
  @override
  void setOnBoardingState(_i9.OnBoardingState? state) =>
      super.noSuchMethod(Invocation.method(#setOnBoardingState, [state]),
          returnValueForMissingStub: null);
}
