version: '2.1'

services:
  wayat_build:
    image: flutter_local:3.3.6
    command: bash -c "cd /workspace/wayat && flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs && flutter build web --web-renderer canvaskit --dart-define=BROWSER_IMAGE_DECODING_ENABLED=false"
    volumes:
      - ./frontend:/workspace/wayat
    env_file:
      - ./frontend/.env