version: '2.1'

services:
  wayat_build:
    image: flutter_local:3.3.6
    command: bash -c "cd /workspace/wayat && flutter pub get && flutter test"
    volumes:
      - ./frontend:/workspace/wayat
    env_file:
      - ./frontend/.env