// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQuE7sYC4QmKa5evrBZq2j0AxbPlQQUvA',
    appId: '1:887276025973:web:d5eb7cea81dfddb45e203c',
    messagingSenderId: '887276025973',
    projectId: 'wayat-flutter',
    authDomain: 'wayat-flutter.firebaseapp.com',
    storageBucket: 'wayat-flutter.appspot.com',
    measurementId: 'G-BQDME1BP0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgT8yt4cmzRkDa0o2i8OtIysNuKDWkwDA',
    appId: '1:887276025973:android:6c3e7cb0dee02ba15e203c',
    messagingSenderId: '887276025973',
    projectId: 'wayat-flutter',
    storageBucket: 'wayat-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjVkDrHneMPPETPX_gAR799lGkppbTdHo',
    appId: '1:887276025973:ios:22652eca1c1a60ba5e203c',
    messagingSenderId: '887276025973',
    projectId: 'wayat-flutter',
    storageBucket: 'wayat-flutter.appspot.com',
    iosClientId: '887276025973-tvck2s564me0tcf5b55np2o09gakns41.apps.googleusercontent.com',
    iosBundleId: 'com.example.spikeFiredart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjVkDrHneMPPETPX_gAR799lGkppbTdHo',
    appId: '1:887276025973:ios:22652eca1c1a60ba5e203c',
    messagingSenderId: '887276025973',
    projectId: 'wayat-flutter',
    storageBucket: 'wayat-flutter.appspot.com',
    iosClientId: '887276025973-tvck2s564me0tcf5b55np2o09gakns41.apps.googleusercontent.com',
    iosBundleId: 'com.example.spikeFiredart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQuE7sYC4QmKa5evrBZq2j0AxbPlQQUvA',
    appId: '1:887276025973:web:f46612d874c45a0a5e203c',
    messagingSenderId: '887276025973',
    projectId: 'wayat-flutter',
    authDomain: 'wayat-flutter.firebaseapp.com',
    storageBucket: 'wayat-flutter.appspot.com',
    measurementId: 'G-9ZGDJPL8D5',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAQuE7sYC4QmKa5evrBZq2j0AxbPlQQUvA',
    appId: '1:887276025973:web:814a32e097fdf35b5e203c',
    messagingSenderId: '887276025973',
    projectId: 'wayat-flutter',
    authDomain: 'wayat-flutter.firebaseapp.com',
    storageBucket: 'wayat-flutter.appspot.com',
    measurementId: 'G-TT0LVPH0TS',
  );
}
